source 'http://rubygems.org'

ruby '2.0.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.2'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# user management
gem 'devise'

# js
gem 'therubyracer'

# Design: bootstrap 3
gem "less-rails"
gem 'date_validator'
gem 'bootstrap_forms', git: 'https://github.com/gagalago/bootstrap_forms'

# admin interface: github: compatible with RoR 4.0
gem 'activeadmin', git: 'https://github.com/gregbell/active_admin.git'

# manage rights
gem 'cancan'
gem 'rolify', '~> 3.3.0.rc4' # rc4 => https://github.com/EppO/rolify/issues/183

#country
gem 'countries'
gem 'country_select'

#paperclip
#gem "paperclip", :git => "git://github.com/thoughtbot/paperclip.git"
gem "paperclip-dropbox", ">= 1.1.7"

#geokit
gem 'geokit-rails'

# coveralls: https://coveralls.io/r/matttbe/SIT
gem 'coveralls', require: false

#infinite scroll
gem 'will_paginate', '~> 3.0'

#Some UI Components
gem "jquery-ui-rails"

gem 'bootstrap-datepicker-rails'

#merit
gem 'merit'
####### Group #######

# tests
group :test do
  gem 'cucumber-rails', :require => false
  # database_cleaner is not required, but highly recommended
  gem 'database_cleaner'
  gem "capybara"
  gem "launchy"
  gem "guard-cucumber"
  gem "rb-readline", "~> 0.5.0"
end

# DB
group :development, :test do
  # Use sqlite3 as the database for Active Record
  gem 'sqlite3'
  gem 'dotenv-rails', :groups => [:development, :test]
end

# production
group :production do
  # Use postgresql as the database for Active Record
  gem 'pg'
  # needed for Heroku
  gem 'rails_12factor'
  # heroku addon
  gem 'newrelic_rpm'
end

####### Misc #######

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
