language: ruby
rvm:
  - "2.0.0"

## multijobs: can be useful if we have hundreds of tests...
# env:
#   - CARD_SET=services
#   - CARD_SET=users
#   - CARD_SET=search

script:
  - rake db:test:purge
  - rake db:test:prepare
#  - bundle exec --verbose cucumber -f progress -r features features/$CARD_SET
  - rake cucumber

before_script:
  # go to the right directory
  - cd website/Solidare-IT-g6
  # Needed for selenium browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # postgres instead of sqlite3
  - cp config/database.yml.travis config/database.yml
  - sed -i "s/sqlite3/pg/g" Gemfile
  - psql -c 'create database SolidareITg6_test;' -U postgres
  # Install dependences
  - travis_retry bundle install --verbose
  # Env
  - cp .env.travis .env
