language: ruby
rvm:
  - "2.0.0"
env:
  - CARD_SET=services
  - CARD_SET=users
script:
  - RAILS_ENV=test bundle exec --verbose rake db:reset --trace
  - bundle exec --verbose cucumber -f progress -r features features/$CARD_SET

before_script:
  # go to the right directory
  - cd website/Solidare-IT-g6
  # Needed for selenium browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # postgres instead of sqlite3
  - cp config/database.yml.travis config/database.yml
  - sed -i "s/sqlite3/pg/g" Gemfile
  - psql -c 'create database SolidareITg6_test;' -U postgres
  # Install dependences
  - bundle install --verbose
